global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: # 200 台の VM の IP を列挙 or file_sd
          - "10.0.1.1:9100"
  - job_name: "backend"
    static_configs:
      - targets: ["backend:4000"]
