apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Timescale
    type: postgres
    url: postgres:5432
    database: lab
    user: postgres
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
